### ISSUE TITLE
Add LICENSE.txt

### ISSUE THREAD

**Issue by Scorpiion** [molview/molview#1]
It is more more less industry practice to include a file called "LICENSE.txt" at the top level of open source projects to indicate how it's licensed. 

It would be nice if you have the time to add one, as I understand from your homepage it should be AGPL, here is a link to the AGPL license you can copy into "LICENSE.txt" if that is the correct license.

https://www.gnu.org/licenses/agpl.txt

**Comment by hermanbergwerf** [comment]
You're right. I was about to add one but there was no code in this repository yet. I'll update it with a license.

**Comment by Scorpiion** [comment]
:+1:
