### ISSUE TITLE
Links not rendering in information cards view.

### ISSUE THREAD

**Issue by gaursagar** [molview/molview#19]
![selection_069](https://user-images.githubusercontent.com/5920942/34482724-d87f5ecc-efdf-11e7-873c-fbdc79f7fc7d.png)

I believe, the text (highlighted) is supposed to be rendered as hyperlinks.

**Comment by bergwerf** [comment]
Correct. I observed this as well but I'm not really maintaining this anymore. This fix should be very simple though, I'll look into it.

**Comment by bergwerf** [comment]
Fixed in 0c5656a7b74286ade77f22a16155bf6472f3f860
