### ISSUE TITLE
Packaging for sandstorm

### ISSUE THREAD

**Issue by zeigerpuppy** [molview/molview#2]
I'd like to try packaging molview for sandstorm,
which repositories are necessary for building the web app?

**Comment by hermanbergwerf** [comment]
The current MolView is entirely in https://github.com/molview/molview-1st-gen, installation instructions are in the README. The new version has not much available yet.

In case you are planning to redistribute MolView using standstorm, please note that proprietary redistribution is not allowed under the terms of the AGPLv3 license. Also please make clear it is an 'unofficial' distribution (in the title and the description).

**Comment by zeigerpuppy** [comment]
Thanks for the details.
The Sandstorm adaptation will remain open with the same licence (AGPLv3).  I'll make sure that it's clear that it's an unofficial version.

**Comment by hermanbergwerf** [comment]
Awesome! Let me know when you have more questions. Maybe we can make an official version in the future :-)
